### PR TITLE
Redesign blog

### PR DESCRIPTION
**Pull request by acacheung**
screen shot 2016-03-05 at 11 14 05 am
screen shot 2016-03-05 at 11 14 14 am

### CODE REVIEW

**Comment by acacheung** [comment]
@indirect @arthurnn @dwradcliffe :smile:

**Comment by duckinator** [comment]
@indirect do you want me to go through and review this?

**Comment by arthurnn** [comment]
@duckinator I will go ahead an merge this.. If you spot any problems on the blog, fell free to send a PR, and cc me.

Indeed this will be hard to review as it is a huge change, but overall looks good. Thanks a lot @acacheung

**Comment by acacheung** [comment]
:smile_cat:

**Comment by simi** [comment]
:tada:

**Pull request merged**
