### PR TITLE
add postmortem for Aug 10 2015

### PR DESCRIPTION
**Pull request by dwradcliffe**
Review please @andremedeiros @evanphx @qrush @skottler @indirect :smile:

### CODE REVIEW

**Comment by indirect** [comment]
:+1:

**Comment by andremedeiros** [comment]
We're off by 1% in the 95% of the successful requests and 4% that failed. Am I missing something?

**Comment by dwradcliffe** [comment]
Hit rate is about 95%. Looking again, it's really 88%, so with 4% failing, that means about 8% were not cached and still successful during that period. I've updated the wording a little bit.

**Comment by andremedeiros** [comment]
:shipit:

**Pull request merged**
