### PR TITLE
Post describing TLSv1.0 and 1.1 phase-out.

### PR DESCRIPTION
**Pull request by indirect**

### CODE REVIEW

**Comment by hsbt** [comment]
Is it caused by the policy of fastly?

**Comment by claudijd** [comment]
@indirect @dwradcliffe nice write up!

**Comment by indirect** [comment]
@hsbt it is partly because of Fastly, and partly because of industry-wide events. TLSv1.0 and TLSv1.1 are no longer secure. Because they are not secure, using them creates a false idea of security, so it is better to not use them at all. 👍

**Comment by dwradcliffe** [comment]
👍🏻

**Comment by hsbt** [comment]
@indirect I understood. It's reasonable for me.

**Pull request merged**
